# Sets the maximum number of ticks to predict. MAX 4 ticks.
# Larger values may lead to inaccurate predicted positions or exploit lag compensation.
max-predict-ticks: 4

# Whether to predict knockback. This will increase the KB's response speed, but the predicted position may be inaccurate.
predict-velocity: true

# How many ticks ahead to predict the sprint. -1 is unlimited.
max-sprint-ticks: 0