name: PlayerLagCompensation
version: '${project.version}'
main: net.azisaba.playerlagcompensation.PlayerLagCompensation

depend:
  - GrimAC

softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

loadbefore:
  - GrimAC
#  - CrackShot

#commands:
#  compensatedcountdown:
