name: PlayerLagCompensation
version: '${project.version}'
main: net.azisaba.playerlagcompensation.PlayerLagCompensation

depend:
  - ProtocolLib
  - GrimAC
  - CrackShot

commands:
  compensatedcountdown:
