name: PlayerLagCompensation
version: '${project.version}'
main: net.azisaba.playerlagcompensation.PlayerLagCompensation

softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

loadbefore:
  - GrimAC

commands:
  togglecompensation:
    permission: playerlagcompensation.command.toggle
  togglevelocitycompensation:
    permission: playerlagcompensation.command.togglevelocity

permissions:
  playerlagcompensation.command.toggle:
    default: op
  playerlagcompensation.command.togglevelocity:
    default: op

